apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-map
  namespace: wenzhou
  labels:
    app: config-server-map
data:
  images.version: 0.1-SNAPSHOT
  application.prefix: wenzhou-
  zookeeper_connect_string: zookeeper:2181
  native_search_location: /home/k8s_apps/wenzhou/config-repo 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  generation: 1
  labels:
    app: config-server
  name: config-server
  namespace: wenzhou
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: ' -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 '
        image: rock007/wenzhou-configserver:v1
        env:
          - name: NATIVE_SEARCH_LOCATIONS
            valueFrom:
              configMapKeyRef:
                name: config-server-map
                key: native_search_location
        envFrom:
          - configMapRef:
            name: config-server-map
        imagePullPolicy: Always
        name: config-server
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /home/k8s-apps/logs
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
