apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespace: wenzhou
spec:
  containers:
  - name: zookeeper
    image: zookeeper:3.6
    ports:
    - containerPort: 2181
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
    - name: data
      emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service 
  namespace: wenzhou
spec:     
  selector:     
    app: zookeeper  
  ports:
    -protocol: TCP     
     port: 2181          
     nodePort: 30006   
     targetPort: 2181  
  type: NodePort  
 