apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: wenzhou
data:
  redis-config: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru   

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: wenzhou
spec:
  containers:
  - name: redis
    image: redis
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-config
        items:
        - key: redis-config
          path: redis.conf

---

apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: wenzhou
spec:
  type: NodePort  
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30007
  selector:
    app: redis              