apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort  ##指定nodePort端口，不填默认为ClusterIP，由系统来维护端口
  ports:
    # 默认情况下，为了方便起见，`targetPort` 被设置为与 `port` 字段相同的值。
    - port: 6379
      targetPort: 6379
      # 可选字段
      # 默认情况下，为了方便起见，Kubernetes 控制平面会从某个范围内分配一个端口号（默认：30000-32767）
      nodePort: 30007
  selector:
    app: redis